addClassPath(".");
MAIN_DIRECTORY = new File(getSourceFileInfo()).getParentFile().getAbsolutePath();
String LOG_FILE = MAIN_DIRECTORY + "/log.txt";
long LONG_CLICK_DURATION = 500;
cd(MAIN_DIRECTORY);
addClassPath(".");
importCommands("main");
importCommands("window");
importCommands("gestures");
importCommands("actions");
importCommands("others");
importCommands("assist");
importCommands("helper");
importCommands("lib");
importCommands("lib.file");
importCommands("assist.helper");
importCommands("assist.dialog");
importCommands("event");
importCommands("global");
importCommands("config");
import android.view.accessibility.*;
if (ENV == void) ENV = Environment();
if (ENV.MACRODROID) {
	This helper = macrodroidHelper();
	helper.set();
}
if (NodeInfo == void) NodeInfo = NodeInfo();
if (WindowInfo == void) WindowInfo = WindowInfo();
if (logIncludeNode == void ) logIncludeNode = false;
if (limitParentLevel == void) limitParentLevel = 1;
if (A11yConfig == void) A11yConfig = A11yConfig();
